#!/usr/bin/env python3
"""
emissions_publish_draft.py — Review and publish blog drafts for DirtiestShips.

Generated by emissions_blog_generator.py. Drafts live in:
  - blog/posts/drafts/{slug}.md     (content)
  - json/blog_drafts.json           (metadata)

Actions per draft:
  [p]ublish   — publish immediately (moves to blog/posts/, adds to blog.json)
  [s]chedule  — set a future date; auto-published by check_scheduled_emissions.py
  [d]elete    — permanently remove draft
  Enter/skip  — leave unchanged

Usage:
    python emissions_publish_draft.py            # interactive list
    python emissions_publish_draft.py --list     # list only, no action
"""

import os
import re
import sys
import json
import subprocess
from datetime import datetime

BASE_DIR     = os.path.dirname(os.path.abspath(__file__))
DRAFTS_DIR   = os.path.join(BASE_DIR, "blog", "posts", "drafts")
POSTS_DIR    = os.path.join(BASE_DIR, "blog", "posts")
BLOG_DRAFTS  = os.path.join(BASE_DIR, "json", "blog_drafts.json")
BLOG_JSON    = os.path.join(BASE_DIR, "json", "blog.json")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_json(path: str, default):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return default


def save_json(path: str, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def list_drafts() -> list:
    """Return sorted list of draft metadata (newest first)."""
    drafts = load_json(BLOG_DRAFTS, {"posts": []})
    posts = drafts.get("posts", [])
    return sorted(posts, key=lambda x: x.get("date", ""), reverse=True)


def print_draft_list(drafts: list):
    if not drafts:
        print("\n  No drafts found. Run emissions_blog_generator.py first.\n")
        return
    print(f"\n  {'#':>3}  {'Score':>5}  {'Date':<12}  {'Scheduled':<17}  Title")
    print("  " + "-" * 80)
    for i, d in enumerate(drafts, start=1):
        title     = d.get("title", d["slug"])[:45]
        score     = d.get("score", "?")
        date      = d.get("date", "?")
        scheduled = d.get("scheduled") or "-"
        print(f"  {i:>3}  {score:>5}  {date:<12}  {scheduled:<17}  {title}")
    print()


def preview_draft(slug: str):
    path = os.path.join(DRAFTS_DIR, f"{slug}.md")
    if not os.path.exists(path):
        print(f"\n  (no .md file found at blog/posts/drafts/{slug}.md)\n")
        return
    print("\n" + "=" * 70)
    with open(path, encoding="utf-8") as f:
        for i, line in enumerate(f):
            if i >= 60:
                print("  ... (truncated)")
                break
            print(line, end="")
    print("=" * 70 + "\n")


# ---------------------------------------------------------------------------
# Publish
# ---------------------------------------------------------------------------

def publish_draft(meta: dict) -> bool:
    slug = meta["slug"]
    src  = os.path.join(DRAFTS_DIR, f"{slug}.md")
    dst  = os.path.join(POSTS_DIR,  f"{slug}.md")

    if not os.path.exists(src):
        print(f"\n  ERROR: Draft file not found: {src}\n")
        return False

    if os.path.exists(dst):
        overwrite = input(f"\n  WARNING: {slug}.md already exists in blog/posts/.\n  Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("  Cancelled.\n")
            return False

    # Move file to blog/posts/
    with open(src, encoding="utf-8") as f:
        content = f.read()
    with open(dst, "w", encoding="utf-8") as f:
        f.write(content)
    os.remove(src)

    # Add to blog.json
    published = load_json(BLOG_JSON, {"posts": []})
    entry = {
        "slug":    meta["slug"],
        "title":   meta["title"],
        "date":    meta["date"],
        "excerpt": meta.get("excerpt", ""),
        "author":  meta.get("author", "DirtiestShips"),
    }
    if meta.get("featured_image"):
        entry["featured_image"] = meta["featured_image"]
    if meta.get("source_url"):
        entry["source_url"] = meta["source_url"]

    # Insert at front (newest first)
    published["posts"].insert(0, entry)
    save_json(BLOG_JSON, published)

    # Remove from blog_drafts.json
    drafts = load_json(BLOG_DRAFTS, {"posts": []})
    drafts["posts"] = [p for p in drafts["posts"] if p["slug"] != slug]
    save_json(BLOG_DRAFTS, drafts)

    print(f"\n  Published → blog/posts/{slug}.md")
    print(f"  Added to json/blog.json")
    return True


# ---------------------------------------------------------------------------
# Schedule
# ---------------------------------------------------------------------------

def schedule_draft(meta: dict) -> bool:
    slug = meta["slug"]

    while True:
        raw = input("  Schedule for (YYYY-MM-DD HH:MM): ").strip()
        try:
            datetime.strptime(raw, "%Y-%m-%d %H:%M")
            break
        except ValueError:
            print("  Invalid format — use YYYY-MM-DD HH:MM (e.g. 2026-03-01 09:00)")

    drafts = load_json(BLOG_DRAFTS, {"posts": []})
    for p in drafts["posts"]:
        if p["slug"] == slug:
            p["scheduled"] = raw
            break
    save_json(BLOG_DRAFTS, drafts)
    print(f"\n  Scheduled → {slug} will publish at {raw}")
    return True


# ---------------------------------------------------------------------------
# Git push
# ---------------------------------------------------------------------------

def git_push(slug: str, action: str = "publish"):
    env = os.environ.copy()
    env["GIT_SSH_COMMAND"] = (
        "ssh -i /home/jeroen/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
    )
    try:
        if action == "publish":
            subprocess.run(
                ["git", "add",
                 f"blog/posts/{slug}.md",
                 "blog/posts/drafts/",
                 "json/blog.json",
                 "json/blog_drafts.json"],
                check=True, cwd=BASE_DIR, env=env,
            )
            msg = f"Publish blog post: {slug}"
        else:  # schedule
            subprocess.run(
                ["git", "add", "json/blog_drafts.json"],
                check=True, cwd=BASE_DIR, env=env,
            )
            msg = f"Schedule blog post: {slug}"

        subprocess.run(["git", "commit", "-m", msg], check=True, cwd=BASE_DIR, env=env)
        subprocess.run(["git", "push"], check=True, cwd=BASE_DIR, env=env)
        print("  Committed and pushed to GitHub.")
    except subprocess.CalledProcessError as e:
        print(f"  Git error: {e}")
        print("  Commit/push manually when ready.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if "--list" in sys.argv:
        print_draft_list(list_drafts())
        return

    while True:
        drafts = list_drafts()
        if not drafts:
            print("\n  No drafts to publish. Run emissions_blog_generator.py first.\n")
            break

        print_draft_list(drafts)
        print("  Commands:  <number> to select  |  q to quit")
        choice = input("  > ").strip().lower()

        if choice in ("q", "quit", "exit", ""):
            break

        try:
            idx = int(choice) - 1
            assert 0 <= idx < len(drafts)
        except (ValueError, AssertionError):
            print("  Invalid choice.\n")
            continue

        meta = drafts[idx]
        print(f"\n  Draft:   {meta['slug']}")
        print(f"  Title:   {meta.get('title', '?')}")
        print(f"  Score:   {meta.get('score', '?')}")
        print(f"  Source:  {meta.get('source_url', '?')}")
        print(f"  Date:    {meta.get('date', '?')}")
        if meta.get("scheduled"):
            print(f"  Scheduled: {meta['scheduled']}")
        print()

        show = input("  Show preview? [Y/n]: ").strip().lower()
        if show != "n":
            preview_draft(meta["slug"])

        action = input(
            "  Action: [p]ublish now  [s]chedule  [d]elete  [enter] skip  > "
        ).strip().lower()

        if action == "p":
            if publish_draft(meta):
                push = input("  Push to GitHub now? [Y/n]: ").strip().lower()
                if push != "n":
                    git_push(meta["slug"], "publish")

        elif action == "s":
            if schedule_draft(meta):
                push = input("  Push scheduled draft to GitHub now? [Y/n]: ").strip().lower()
                if push != "n":
                    git_push(meta["slug"], "schedule")

        elif action == "d":
            confirm = input(
                f"  DELETE {meta['slug']} permanently? [y/N]: "
            ).strip().lower()
            if confirm == "y":
                # Remove .md file
                md_path = os.path.join(DRAFTS_DIR, f"{meta['slug']}.md")
                if os.path.exists(md_path):
                    os.remove(md_path)
                # Remove from blog_drafts.json
                all_drafts = load_json(BLOG_DRAFTS, {"posts": []})
                all_drafts["posts"] = [p for p in all_drafts["posts"] if p["slug"] != meta["slug"]]
                save_json(BLOG_DRAFTS, all_drafts)
                print(f"  Deleted {meta['slug']}.\n")

        else:
            print("  Skipped.\n")


if __name__ == "__main__":
    main()
